title: Windows Server Talks
description: DFS, Active Directory, Hyper-V, and PowerShell guides
baseurl: "/WindowsServerTalks"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

just_the_docs:
  search_enabled: true
