
title: "Windows Server Talks"
description: "DFS, Active Directory, Hyperâ€‘V, and PowerShell Guides by Mohit Maurya"

theme: jekyll-theme-cayman

markdown: kramdown
highlighter: rouge

include:
  - "_pages"
  - "assets"

collections:
  docs:
    output: true

sass:
  style: compressed

github:
  is_project_page: true
