
title: "Windows Server Talks"
description: "DFS, Active Directory, Hyperâ€‘V, and PowerShell Guides by Mohit Maurya"

url: "https://mauryamohit07.github.io"
baseurl: "/WindowsServerTalks"   # EXACT repo name

theme: jekyll-theme-cayman
markdown: kramdown
highlighter: rouge

include:
  - _includes
  - assets
  - images

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
