
title: "Windows Server Talks"
description: "DFS, Active Directory, Hyperâ€‘V, and PowerShell Guides by Mohit Maurya"

theme: jekyll-theme-cayman
baseurl: "/WindowsServerTalks"
url: "https://mauryamohit07.github.io"

markdown: kramdown
theme: jekyll-theme-cayman

markdown: kramdown
highlighter: rouge

include:
  - _includes
  - docs

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
